apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: ClusterOriginIssuer
metadata:
  name: mtps.pl-cf
  namespace: cert-manager
spec:
  requestType: OriginECC
  auth:
    tokenRef:
      name: cfapi-mtps.pl-ssl
      key: token
