apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: apps-vol
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: '3'
  staleReplicaTimeout: '2880'
  diskSelector: apps
  allowVolumeCreation: "true"